name: ship-deliverable
on:
  workflow_dispatch:
    inputs:
      export_to_github:
        description: "Commit deliverables to 'deliverable' branch"
        required: false
        default: "true"
        type: choice
        options: ["true", "false"]
      export_to_notion:
        description: "Push to Notion (requires secrets)"
        required: false
        default: "false"
        type: choice
        options: ["true", "false"]
  pull_request:
    branches: [ main ]

permissions:
  contents: write    # needed to push 'deliverable' on non-PR runs
  actions: read
  checks: read

jobs:
  ship:
    runs-on: ubuntu-latest
    concurrency:
      group: ship-${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.name }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        config: 
          - { name: "standard", answers: "answers.ci.json", export_to_github: false }
          - { name: "enterprise", answers: "answers.enterprise.ci.json", export_to_github: true }
    env:
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      GITHUB_BRANCH: deliverable
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Prepare CI answers
        run: |
          if [ ! -f answers.json ] && [ -f "${{ matrix.config.answers }}" ]; then
            cp "${{ matrix.config.answers }}" answers.json
            echo "✓ Using ${{ matrix.config.answers }} for CI build (${{ matrix.config.name }})"
          elif [ -f answers.json ]; then
            echo "✓ Using existing answers.json"
          else
            echo "✗ No answers file found (missing both answers.json and ${{ matrix.config.answers }})"
            exit 1
          fi

      - name: Verify agent policies
        run: node scripts/verify-agent-policy.js
      - name: Install deps (ci)
        run: npm ci --no-audit --no-fund

      - name: CI structure self-check
        run: npm run ci:selfcheck

      - name: E2E (dry) - questionnaire + lecun
        env:
          TZ: UTC
          LC_ALL: C
          LANG: C
          NODE_ENV: test
        run: npm run test:e2e

      - name: Ship pipeline
        env:
          TZ: UTC
          LC_ALL: C
          LANG: C
          NODE_ENV: production
          NOTION_TOKEN: ${{ inputs.export_to_notion == 'true' && secrets.NOTION_TOKEN || '' }}
          NOTION_PARENT_PAGE_ID: ${{ inputs.export_to_notion == 'true' && secrets.NOTION_PARENT_PAGE_ID || '' }}
        run: npm run ship -- --answers=${{ matrix.config.answers }}
      - name: Verify artifact integrity (SHA-256 + manifest)
        run: node scripts/verify-artifacts.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deliverables-${{ matrix.config.name }}
          path: |
            outputs/generated-deliverable.md
            outputs/generated-deliverable.html
            outputs/generated-deliverable.pdf
            outputs/manifest.json
          if-no-files-found: error
          retention-days: 14

      - name: Export to deliverable branch (only on non-PR runs)
        if: ${{ matrix.config.export_to_github == true && github.event_name != 'pull_request' }}
        env:
          GIT_AUTHOR_NAME: ci-bot
          GIT_AUTHOR_EMAIL: ci-bot@example.com
          GIT_COMMITTER_NAME: ci-bot
          GIT_COMMITTER_EMAIL: ci-bot@example.com
        run: |
          set -euo pipefail
          git fetch origin deliverable || true
          git checkout -B deliverable
          mkdir -p ./_dl
          rsync -a --delete outputs/ ./_dl/outputs/
          rsync -a .ship/ ./_dl/.ship/ || true
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "ci: export deliverable for ${{ matrix.config.name }} ($GITHUB_SHA)"
            git push origin deliverable --force
          else
            echo "No changes to export."
          fi
